import 'package:first_mobile/model/course.dart';
import 'package:first_mobile/model/course_category.dart';
import 'package:first_mobile/model/section.dart';

class CourseDataProvider {
  static final List<Section> sectionList = [
    Section(
      id: 'introduction',
      title: 'Introduction',
      content:
          'Introduction • What is Flutter • Understanding Flutter Architecture • Flutter Alternatives',
    ),
    Section(
      id: 'basics',
      title: 'Flutter Basics',
      content:
          'Module Introduction • Creating New Project • Dart Basics • Dart Fundamentals • Flutter App Basic',
    ),
    Section(
      id: 'layouts',
      title: 'Layouts',
      content: 'Module Introduction • Creating New Project • Flutter App Basic',
    ),
    Section(
      id: 'responsive',
      title: 'Responsive & Adaptive UI',
      content:
          'Module Introduction • Dart Basics • Dart Fundamentals • Flutter App Basic',
    ),
    Section(
      id: 'real_app',
      title: 'Building Real App',
      content: 'Module Introduction • Creating New Project • Flutter App Basic',
    ),
  ];

  static final List<Course> courseList = [
    Course(
      id: "1",
      title: "Flutter Master class",
      thumbnailUrl: "assets/images/aoi8.png",
      description:
          "This complete flutter development course from beginner to expert. Flutter is Google’s mobile UI open source framework to build high-quality native (super fast) interfaces for iOS and Android apps with the unified codebase.",
      createdBy: "Effortless Code Learning",
      createdDate: "01-Jan-2022",
      rate: 4.2,
      isFavorite: false,
      courseCategory: CourseCategory.programming,
      price: 100,
      duration: '2.5 Hours',
      lessonNo: 15,
      sections: sectionList,
      youtubeUrl: 'https://www.youtube.com/watch?v=PhdbqhUbNnQ',
    ),
    Course(
      id: "2",
      title: "Flutter with Firebase",
      thumbnailUrl: "assets/images/aoi7.png",
      description:
          "Flutter is Google’s mobile UI open source framework to build high-quality native (super fast) interfaces for iOS and Android apps with the unified codebase.",
      createdBy: "Effortless Code Learning",
      createdDate: "01-Apr-2022",
      rate: 4.5,
      isFavorite: false,
      courseCategory: CourseCategory.programming,
      price: 50,
      duration: '3 Hours',
      lessonNo: 10,
      sections: sectionList,
      youtubeUrl: 'https://www.youtube.com/watch?v=WlSG3pEQMRg',
    ),
    Course(
      id: "3",
      title: "Complete Web 3.0",
      thumbnailUrl: "assets/images/aoi9.png",
      description:
          "Welcome to Become a Blockchain Developer with Ethereum and Solidity! This course is a complete introduction to decentralized application (Dapp) development.",
      createdBy: "Perfect Academy",
      createdDate: "01-Mar-2022",
      rate: 5,
      isFavorite: false,
      courseCategory: CourseCategory.programming,
      price: 75,
      duration: '2.7 Hours',
      lessonNo: 15,
      sections: sectionList,
      youtubeUrl: 'https://www.youtube.com/watch?v=M3BM9TB-8yA',
    ),
    Course(
      id: "4",
      title: "Learn Programming Trick",
      thumbnailUrl: "assets/images/aoi8.png",
      description:
          "One of the common and basic questions among students or someone who wants to learn code is “How can I learn to code fast and make a career as a programmer?”. Whether you are a student, fresher or experienced person trying to switch your job in programming you will definitely try to find tips and tricks to learn programming quickly and effectively",
      createdBy: "Effortless Code Learning",
      createdDate: "01-Jan-2022",
      rate: 4,
      isFavorite: false,
      courseCategory: CourseCategory.programming,
      price: 40,
      duration: '5 Hours',
      lessonNo: 30,
      sections: sectionList,
      youtubeUrl: 'https://www.youtube.com/watch?v=kuirGzjMVQE',
    ),
    Course(
      id: "5",
      title: "Complete React Course",
      thumbnailUrl: "assets/images/aoi7.png",
      description:
          "This course is fully up-to-date with React 18 (the latest version of React)!\nIt was completely updated and re-recorded from the ground up - it teaches the very latest version of React with all the core, modern features you need to know!",
      createdBy: "Effortless Code Learning",
      createdDate: "01-Jan-2022",
      rate: 4.5,
      isFavorite: false,
      courseCategory: CourseCategory.programming,
      price: 120,
      duration: '4.3 Hours',
      lessonNo: 25,
      sections: sectionList,
      youtubeUrl: 'https://www.youtube.com/watch?v=x0DnXxQ1CqE',
    ),
    Course(
      id: "6",
      title: "Learn Marketing",
      thumbnailUrl: "assets/images/heroo.png",
      description:
          "This is complete marketing master class. In this course, you will learn how to increase sales, approach new clients.",
      createdBy: "ECL",
      createdDate: "01-MAR-2022",
      rate: 4.2,
      isFavorite: false,
      courseCategory: CourseCategory.marketing,
      price: 150,
      duration: '4 Hours',
      lessonNo: 20,
      sections: sectionList,
      youtubeUrl: 'https://www.youtube.com/watch?v=W7NeRiNI0A0',
    ),
    Course(
      id: "7",
      title: "Marketing MasterClass",
      thumbnailUrl: "assets/images/logo.png",
      description:
          "You're looking for a complete digital marketing course to teach you everything you need to become a digital marketing expert, right?",
      createdBy: "Effortless Code Learning",
      createdDate: "01-Jan-2022",
      rate: 4.7,
      isFavorite: false,
      courseCategory: CourseCategory.marketing,
      price: 80,
      duration: '4.2 Hours',
      lessonNo: 21,
      sections: sectionList,
      youtubeUrl: 'https://www.youtube.com/watch?v=J7yQTJ3aTnk',
    ),
    Course(
      id: "8",
      title: "How to Increase Sales",
      thumbnailUrl: "assets/images/aoi2.png",
      description:
          "You're looking for a complete digital marketing course to teach you everything you need to become a digital marketing expert, right?",
      createdBy: "Effortless Code Learning",
      createdDate: "01-Apr-2022",
      rate: 4.3,
      isFavorite: false,
      courseCategory: CourseCategory.marketing,
      price: 100,
      duration: '4.5 Hours',
      lessonNo: 20,
      sections: sectionList,
      youtubeUrl: 'https://www.youtube.com/watch?v=VhUvTFxhfJY',
    ),
    Course(
      id: "9",
      title: "Marketing Strategy",
      thumbnailUrl: "assets/images/aoi5.png",
      description: "In this course, you will learn various marketing strategy",
      createdBy: "Effortless Code Learning",
      createdDate: "01-June-2022",
      rate: 5,
      isFavorite: false,
      courseCategory: CourseCategory.marketing,
      price: 120,
      duration: '3.5 Hours',
      lessonNo: 32,
      sections: sectionList,
      youtubeUrl: 'https://www.youtube.com/watch?v=r4a_G8tiwrI',
    ),
    Course(
      id: "10",
      title: "Invest Money Wisely",
      thumbnailUrl: "assets/images/aoi6-1.png",
      description:
          "In this course, you will learn invest money wisely in various categories. Learn basic of capital market, other debt options.",
      createdBy: "Effortless Code Learning",
      createdDate: "15-Feb-2022",
      rate: 5,
      isFavorite: false,
      courseCategory: CourseCategory.finance,
      price: 100,
      duration: '6 Hours',
      lessonNo: 35,
      sections: sectionList,
      youtubeUrl: 'https://www.youtube.com/watch?v=0dU8k3OFpxY',
    ),
    Course(
      id: "11",
      title: "Crypto Technical Analysis",
      thumbnailUrl: "assets/images/aoi8-2.png",
      description:
          "In this course, you will learn thorough crypto technical analysis. It will covers basic understanding on various crypto currencies. Volatility in crypto market.",
      createdBy: "Effortless Code Learning",
      createdDate: "15-Feb-2022",
      rate: 4.6,
      isFavorite: false,
      courseCategory: CourseCategory.finance,
      price: 90,
      duration: '3 Hours',
      lessonNo: 22,
      sections: sectionList,
      youtubeUrl: 'https://www.youtube.com/watch?v=PUPwT41p5A4',
    ),
    Course(
      id: "12",
      title: "All about Crypto",
      thumbnailUrl: "assets/images/aoi8-3.png",
      description:
          "In this course, you will learn thorough crypto technical analysis. It will covers basic understanding on various crypto currencies. Volatility in crypto market.",
      createdBy: "Effortless Code Learning",
      createdDate: "20-Mar-2022",
      rate: 4.8,
      isFavorite: false,
      courseCategory: CourseCategory.finance,
      price: 75,
      duration: '3.5 Hours',
      lessonNo: 28,
      sections: sectionList,
      youtubeUrl: 'https://www.youtube.com/watch?v=rUHJKrk611s',
    ),
  ];
}
